### ISSUE TITLE
 class file for androidx.appcompat.app.AppCompatActivity not found

### ISSUE THREAD

**Issue by rajkhan91** [capacitor-community/native-market#16]
node_modules\@capacitor-community\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:21: error: cannot access AppCompatActivity
                Context context = this.bridge.getActivity().getApplicationContext();
                                                         ^
  class file for androidx.appcompat.app.AppCompatActivity not found

**Comment by marwenhinnaouii** [comment]
Same issue

**Comment by etomeni** [comment]
Please help fix this issue

**Comment by jcesarmobile** [comment]
I've released 4.0.0 with Capacitor 4 support, it should have fixed this issue.
Also 5.0.0 with Capacitor 5 support.
If the problem is still present, please, create a new issue and provide a sample app that reproduces the issue
