### ISSUE TITLE
Capacitor v3

### ISSUE THREAD

**Issue by djonmayer** [capacitor-community/native-market#7]
If I use this plugin with capacitor v3, I get this error:

`Error: node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    16 Property 'NativeMarket' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.

export interface CapacitorInstance extends CapacitorGlobal {
                    ~~~~~~~~~~~~~~~~~

  node_modules/@capacitor-community/native-market/dist/esm/definitions.d.ts:3:9
     3       NativeMarket: NativeMarketPlugin;
              ~~~~~~~~~~~~
    'NativeMarket' is declared here.`

**Comment by jordanorc** [comment]
Any upgrade on this?

**Comment by Anket-21** [comment]
[https://ionicframework.com/docs/native/market/](url)

You can refer the about Link 💯

**Comment by stefanhk31** [comment]
Are there even instructions for v3? Readme doesn't use the `RegisterPlugin` method that v3 plugins implement. I was hoping that Android Studio would show me a class to import, but no such luck. 

![studio64_xJHv5DACA4](https://user-images.githubusercontent.com/42074868/131402556-56689716-66d1-4261-ab11-447b8a9587b5.png)

**Comment by playaz87** [comment]
Will this be updated for v3? I'm also getting ` Property 'NativeMarket' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'`

**Comment by GosuMania** [comment]
any news???

**Comment by hermitdemschoenenleben** [comment]
this fork works for me with capacitor 3: https://github.com/hermitdemschoenenleben/native-market

**Comment by riderx** [comment]
if you need i published it with capacitor 3 https://www.npmjs.com/package/@capgo/native-market
